[build]
command = "react-router build"
publish = "build/client"

[dev]
command = "react-router dev"

[functions]
included_files = [
    "node_modules/@react-router/**/dist/**",
    "node_modules/react-router/dist/**",
    "node_modules/turbo-stream/dist/**"
  ]
